/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

/**
 *
 * @author hp
 */
public class Return_Management extends javax.swing.JInternalFrame {

    /**
     * Creates new form Return_Management
     */
    public Return_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(1414, 670));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
